//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Administrator
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string User { get; set; }
        public string WoType { get; set; }
        public string Xxfb { get; set; }
        public string Term { get; set; }
        public string Course { get; set; }
        public string Section { get; set; }
        public string Class { get; set; }
        public string Title { get; set; }
        public string Teaching { get; set; }
        public string Course_selection { get; set; }
        public string Question_type { get; set; }
    }
}
