//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course_selection
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Curriculum { get; set; }
        public Nullable<System.DateTime> Term { get; set; }
        public Nullable<System.DateTime> Course { get; set; }
        public string Place { get; set; }
        public string Assessment { get; set; }
    }
}
