//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examination
    {
        public string WName { get; set; }
        public Nullable<System.DateTime> WTime { get; set; }
        public string WCJ { get; set; }
        public string WType { get; set; }
        public string WXH { get; set; }
        public Nullable<System.DateTime> WStime { get; set; }
        public Nullable<System.DateTime> WEtime { get; set; }
    }
}
