//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OTSEntities : DbContext
    {
        public OTSEntities()
            : base("name=OTSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achievement> Achievement { get; set; }
        public virtual DbSet<Administrator> Administrator { get; set; }
        public virtual DbSet<Class> Class { get; set; }
        public virtual DbSet<Course_selection> Course_selection { get; set; }
        public virtual DbSet<Examination> Examination { get; set; }
        public virtual DbSet<Item_bank> Item_bank { get; set; }
        public virtual DbSet<Paper> Paper { get; set; }
        public virtual DbSet<Release> Release { get; set; }
        public virtual DbSet<Student> Student { get; set; }
        public virtual DbSet<Teacher> Teacher { get; set; }
        public virtual DbSet<Teaching> Teaching { get; set; }
        public virtual DbSet<UserInfo> UserInfo { get; set; }
    }
}
