//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace hr.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int XSID { get; set; }
        public string XSName { get; set; }
        public string XSGender { get; set; }
        public string XSEnrollmentYear { get; set; }
        public string Studentclass { get; set; }
        public string Studentgrade { get; set; }
        public string Studentbirth { get; set; }
        public string StudentState { get; set; }
        public string StudentRemarks { get; set; }
    }
}
